Repository lmachens/photoplay, pull requests merged in 2021-06, with the labels that each got.

#81 ✨ Add users collection with API routes
  package-lock.json
  package.json
  samples.http
  src/server.ts
  src/server/db.ts
  src/server/routes.ts
  src/server/users.ts
  src/types.ts
Labels: enhancement

#73 ♻️ Implement api to TVShowDetails
  src/app/App.tsx
  src/app/components/Trailer/Trailer.stories.tsx
  src/app/components/Trailer/Trailer.tsx
  src/app/pages/TVShowDetails/TVShowDetails.module.css
  src/app/pages/TVShowDetails/TVShowDetails.tsx
Labels: enhancement

#84 ✨ Optimize users API responses
  src/server/routes.ts
  src/server/users.ts
Labels: enhancement

#68 💄 Make homescreen page scrollable
  src/app/pages/Homescreen/Homescreen.module.css
Labels: bug, css

#101 👷 Add production build
  package.json
  src/server.ts
  tsconfig.server.json
  vite.config.js
Labels: enhancement

#99 ✨ Implement MultiSearch Endpoint
  samples.http
  src/server/routes.ts
  src/server/theMovieDB.ts
  src/types.ts
Labels: enhancement

#103 🚑 Forward client routing in production
  src/server.ts
Labels: bug

#98 ✨ Register a new user on the Register page
  src/app/components/Button/Button.module.css
  src/app/components/Button/Button.tsx
  src/app/globals.css
  src/app/hooks/useMutation.ts
  src/app/pages/Register/Register.module.css
  src/app/pages/Register/Register.tsx
  src/app/utils/api.ts
Labels: enhancement

#112 Login user and display name on profile page
  samples.http
  src/app/App.tsx
  src/app/components/BackButton/BackButton.module.css
  src/app/components/ErrorMessage/ErrorMessage.module.css
  src/app/components/ErrorMessage/ErrorMessage.stories.tsx
  src/app/components/ErrorMessage/ErrorMessage.tsx
  src/app/components/NavBar/NavBar.tsx
  src/app/env.d.ts
  src/app/hooks/useFetch.ts
  src/app/pages/Login/Login.module.css
  src/app/pages/Login/Login.tsx
  src/app/pages/Profile/Profile.module.css
  src/app/pages/Profile/Profile.tsx
  src/app/pages/Register/Register.module.css
  src/app/pages/Register/Register.tsx
  src/app/utils/api.ts
  src/server/routes.ts
  src/server/users.ts
  vite.config.js
Labels: enhancement

#116 ♻️ Rename CSS variables
  src/app/components/Avatar/Avatar.module.css
  src/app/components/BackButton/BackButton.module.css
  src/app/components/Button/Button.module.css
  src/app/components/EpisodeCard/EpisodeCard.module.css
  src/app/components/ErrorMessage/ErrorMessage.module.css
  src/app/components/Icons/AppIcon.tsx
  src/app/components/Icons/FacebookIcon.tsx
  src/app/components/Icons/ProfilePictureIcon.tsx
  src/app/components/LabeledInput/LabeledInput.module.css
  src/app/components/NavBar/NavBar.module.css
  src/app/components/NavBarLink/NavBarLink.module.css
  src/app/components/NavigationGenre/NavigationGenre.module.css
  src/app/components/ProfileMenuBar/ProfileMenuBar.module.css
  src/app/components/Rating/Star.tsx
  src/app/components/SearchField/SearchField.module.css
  src/app/components/SeriesCard/SeriesCard.module.css
  src/app/components/SocialLogin/SocialLogin.module.css
  src/app/components/SocialLogins/SocialLogins.module.css
  src/app/globals.css
  src/app/pages/ForgotPassword/ForgotPassword.module.css
  src/app/pages/Homescreen/Homescreen.module.css
  src/app/pages/Login/Login.module.css
  src/app/pages/Profile/Profile.module.css
  src/app/pages/Register/Register.module.css
Labels: refactoring
